# Generated by Django 5.1.4 on 2024-12-28 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'mp4', 'jpeg', 'png', 'gif'])])),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], max_length=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
